feat:  lighthouse-ci test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,6 +54,13 @@ jobs:
       - name: Run test
         run: pnpm test
 
+      - name: Run lighthouse-ci
+        run: |
+          pnpm install -g @lhci/cli@0.8.x
+          pnpm build
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
   securityCheck:
     runs-on: ubuntu-latest
     needs: [CI]
